app/models.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: models.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-05 09:56
Desc:  
"""

from werkzeug.security import generate_password_hash
from werkzeug.security import check_password_hash
from flask_login import LoginManager
from flask_login import UserMixin
from . import db
from . import login_manager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


class User(UserMixin, db.Document):
    
    meta = {
        'collection': 'users',
        'ordering': ['-create_at'],
        'strict': False,
    }
    user_id = db.StringField(primary_key=True, required=True)
    user_name = db.StringField(unique=True, required=True)
    password = db.StringField(required=True)
    password_hash = db.StringField(required=True)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


# @login_manager.user_loader
# def load_user(user_id):
#     return User.objects().get_or_404(user_id=user_id)


class Article(db.Document):

    meta = {
        'collection': 'articles',
        'ordering': ['-create_at'],
        'strict': False
    }
    id = db.StringField(primary_key=True, required=True)
    title = db.StringField(unique=True, required=True)
    

app/vca/forms.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: forms.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-07 13:11
Desc:  
"""

from flask_wtf import FlaskForm
from wtforms import SubmitField
from flask_wtf.file import FileField
from flask_wtf.file import FileRequired
from flask_wtf.file import FileAllowed
from werkzeug.utils import secure_filename

from .. import videos


class VideoForm(FlaskForm):
    """
    上传视频表单
    """
    upload = FileField(u'选择文件', validators=[
        FileRequired(),
        FileAllowed(['mp4'], u'支持 .mp4 文件上传')])
    submit = SubmitField(u'上传')

app/__init__.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: __init__.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-05 01:33
Desc: 定义工厂函数，在工厂函数中通过注册蓝本的方式创建程序实例 
"""

from flask import Flask
from flask import render_template
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_mongoengine import MongoEngine
from flask_login import LoginManager
from flask_uploads import UploadSet
from flask_uploads import configure_uploads
from config import config


bootstrap = Bootstrap()
moment = Moment()
db = MongoEngine()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

# 允许上传文件的类型
VIDEOS = tuple('mp4')
videos = UploadSet('videos', VIDEOS)


def create_app(config_name):
    """
    工厂函数
    """
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    configure_uploads(app, (videos))

    from .home import home as home_blueprint
    from .auth import auth as auth_blueprint
    from .vca import vca as vca_blueprint
    from .article import article_bp
    app.register_blueprint(home_blueprint)
    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(vca_blueprint, url_prefix='/vca')
    app.register_blueprint(article_bp, url_prefix='/article')

    return app

app/article/__init__.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: __init__.py
Author: <your-name> (<your-email>)
Date: 2018-03-12 17:09
Desc:  
"""

from flask import Blueprint

article_bp = Blueprint('articles', __name__)

from . import views

app/article/views.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: views.py
Author: <your-name> (<your-email>)
Date: 2018-03-12 17:21
Desc: 文章列表页面视图 
"""

from flask import render_template
from flask import redirect
from flask import url_for
from flask import flash
from flask import request

from . import article_bp
from ..models import Article


@article_bp.route('/feed')
def feed():
    return 'This is article feed page'


@article_bp.route('/<id>')
def article(id):
    return 'This is article id-{} detail page'.format(id)

app/home/__init__.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: __init__.py
Author: huxy29
Date: 2018-03-05 01:38
Desc:  
"""

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: views.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-05 20:42
Desc:  
"""

from flask import render_template
from flask_login import login_required
from . import home
from .. import login_manager
from ..models import User


@home.route('/')
def entry():
    return render_template('home/entry.html')


@login_manager.user_loader
def load_user(user_id):
    return User.objects(user_id=user_id).first()

app/vca/__init__.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: __init__.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-06 15:16
Desc:  
"""

from flask import Blueprint

vca = Blueprint('vca', __name__)

from . import views

app/vca/views.py
#!/usr/bin/env python
# -*- coding: utf8 -*-

"""
File: views.py
Author: %huxiaoyang% (%huxy29@outlook.com%)
Date: 2018-03-06 15:21
Desc:  
"""

import os
import hashlib
from datetime import datetime
from flask import flash
from flask import url_for
from flask import send_from_directory
from flask import render_template
from flask import redirect
from flask import request
from flask_login import login_required
from werkzeug.utils import secure_filename
from . import vca
from .. import videos
from .forms import VideoForm


UPLOAD_FILES_DIR = os.path.abspath(os.path.join(__file__, 
                                                '../../static/upload_files'))


def gen_md5(string):
    m = md5.new()
    m.update(string)
    return m.hexdigest()


def get_datetime():
    return datetime.now().strftime('%Y%m%d%H%M%S')


@vca.route('/', methods=['GET', 'POST'])
def entry_page():
    form = VideoForm()
    if form.validate_on_submit():
        f = form.upload.data
        filename = secure_filename(f.filename)
        filename = get_datetime() + filename 
        if not os.path.exists(UPLOAD_FILES_DIR):
            os.mkdir(UPLOAD_FILES_DIR)
        f.save(os.path.join(
            UPLOAD_FILES_DIR, filename 
        ))
        flash(u'上传成功')
        # 只能传递重定向的视图函数可以接受的参数
        return redirect(url_for('vca.result_page', fileid=filename))
    return render_template('vca/entry_page.html', form=form)


@vca.route('/result/<fileid>')
def result_page(fileid):
    if fileid:
        article = {
            "title": u"这是标题",
            "content": [
                {"image": "https://mdn.mozillademos.org/files/12371/newspaper_small.jpg"},
                {"text": u"https://mdn.mozillademos.org/files/12371/newspaper_small.jpg"}
            ]
        }
        url = url_for('static', filename='upload_files/{}'.format(fileid))
        return render_template('vca/result_page.html', url=url, article=article)
    return redirect(url_for('vca.entry_page'))

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}VAGS 基于视频OCR的文章生成系统{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-cion">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle"
			 data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">VAGS 基于视频OCR的文章生成系统</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="{{ url_for('articles.feed') }}">文章列表</a></li>
				<li><a href="{{ url_for('vca.entry_page') }}">上传视频</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
				<li><a href="/">{{ current_user.username }}</a></li>
				<li><a href="{{ url_for('auth.logout') }}">退出</a></li>
				{% else %}
				<li><a href="{{ url_for('auth.login') }}">登录</a></li>
				<li><a href="{{ url_for('auth.register') }}">注册</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		{{ message }}
	</div>
	{% endfor %}
	<div class="row">
		<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
			{% block auth_content %}{% endblock %}
		</div>
	</div>
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-sm-6 col-sm-offset-3">
			{% block page_content %}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
	{{ super() }}
	{{ moment.include_moment() }}
{% endblock %}

app/templates/footer.html
<h1> HAHA, this is footer </h1>

app/templates/home/entry.html
{% extends "base.html" %}

{% block page_content %}
Hello, 
{% if current_user.is_authenticated %}
	{{ current_user.username }}
{% else %}
	New
{% endif %}
<p>
08年出去旅游跟团的我和我爸一直很要好，所以我平时逛街什么都喜欢勾着我爸爸。同团的一个女的，我估计他已经憋了很久了。终于有一天在车上她问我们，你们俩是？我回答，我们同一个姓，你说呢？然后她尴尬的笑笑我觉得不是你们像不像，而是有些人就喜欢恶意揣测，我爸的确长的挺年轻不显老，而且打扮时髦，而我也正值20岁，但是，俩人差那么多难道你就没点眼力劲？一般我认为看到年轻女孩和年纪大的男得不都应该先联想成父女么？所以说到底这个社会的三观正在腐坏，不是么？再说了，你有见过俩背影走路姿势包括一模一样的干爹和女儿么！

作者：Jessica pan
链接：https://www.zhihu.com/question/24117081/answer/332380128
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
</p>
{% endblock %}

app/templates/macro.html
{% macro show(num) %}
	<li> <h2> {{ num }} </h2> </li>
{% endmacro %}

app/templates/user.html
{% extends 'base.html' %}

{% block title %}Huxy29's Notes{% endblock %}

{% block page_content %}

<div class="container">
	<div class="page-header">
		<h1> Hello, {{ name }} </h1>
		这是用新的继承模板生成的！
	</div>
</div>

{% endblock %}

app/templates/vca/entry_page.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<h1>上传</h1>

{% if form.upload.data.filename %}
<p><a href="http://127.0.0.1/static/upload_files/{{ form.upload.data.filename }}">视频</a></p>
{% endif %}

{{ wtf.quick_form(form)}}

{% endblock %}

app/templates/vca/result_page.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block title %}结果展示{% endblock %}


{% block page_content %}
<!DOCTYPE html>
	<div>
		{% if url %}
		<video width="320" height="240" controls="controls">
			<source src="{{ url }}" type="video/mp4">
		</video>
		{% endif %}
	</div>
	<p>{% if para %}{{ para }}{% endif %}</p>
	<div>
		<p>生成文章：</p>
		{% if article %}
		<h1>{{ article['title'] }}</h1>
		{% for content in article['content'] %}
			{% if 'image' in content %}
			<img src="{{ content['image'] }}">
			{% else %}
			<p>{{ content['text'] }}</p>
			{% endif %}
		{% endfor %}
		{% endif %}
	</div>
{% endblock %}